### ISSUE TITLE
Registry

### ISSUE THREAD

**Issue by ggblake** [salabim/salabim#42]
In salabim, what is the Registry and how is it used?

**Comment by salabim** [comment]
What do you mean with the "Registry"?

**Comment by salabim** [comment]
The following classes have a register method:
-  Component
-   Monitor
-   Queue
-   Resource
-   State

This makes it easier to do collective actions on a number of components, monitors, queues, resources and/or states.

A registry is just a list of objects, which can for instance be used as:
```
    monitors = []
    m1 = sim.Monitor(name='m1').register(monitors)
    m2 = sim.Monitor(name='m2').register(monitors)
    queues = []
    q1 = sim.Queue(name='q1').register(queues)
    q2 = sim.Queue(name='q2').register(queues)
    ...
    for obj in monitors + queues:
        obj.print_histograms()
        obj.reset_histograms()
```    
Another example:
```
    components = []
    while(...):
        MyComp().register(components)
    ...
    print('all components in system:')
    for component in components:
        print(component.name())
```

Make sure to deregister any objects that are not used anymore, otherwise, these will not be garbage collected!

Note that it is possible to mix several types of classes in a registry (list).
