### ISSUE TITLE
Documentation: Minor depracted function call for ComponentGenerator

### ISSUE THREAD

**Issue by TueChristensen** [salabim/salabim#47]
Two very minor issues (I think) for the documentation for the ComponentGenerator [here](https://www.salabim.org/manual/ComponentGenerator.html) compared with the reference [here](https://www.salabim.org/manual/Reference.html#componentgenerator)

## Issue 1: name -> generator_name
The documentation mentions that a name can be assigned, however this should be 'generator_name' 

## Issue 2: n -> number

The documentation mentions that a number 'n' can be assigned, however, this should be 'number'

Trying out salabim for the first time now and coming from a beginner level in Arena - I must say I am impressed!

**Comment by salabim** [comment]
Thanks for reporting these issues.

Issue 1:
This is actually correct. By specifying name, this will be 'propagated' to the creating of a Car. So, in the example the cars will be called ford.0, ford.1, ford.2 instead of car.0, car.1, car.2 .

Issue 2:
This is indeed a mistake. I will correct that soon.

On a sideline:
Most communication with and by salabim users is done via the Google Group. May I invite you to join via www.salabim.org (if you are not yet) and leave comments there?

**Comment by TueChristensen** [comment]
Thanks for the quick reply! 

Yea I see that issue 1 was indeed propagation (and used it afterwards).

i will request to join thegoogle groups - thanks!
